---
name: vagrant-box

on:
  push:
    branches: [main, ci]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-box:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install vagrant
        run: |
          brew install vagrant virtualbox

      - name: Build vagrant box
        run: |
          vagrant up --provider virtualbox
          vagrant package --provider virtualbox
