---
name: vagrant-box

on:
  push:
    branches: [main, ci]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-box:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: vagrant up

      - name: Package
        run: vagrant package --output l4s.box default

      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          path: l4s.box
