---
name: vagrant-box

on:
  push:
    branches: [main, ci]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get install -y vagrant
